### ISSUE TITLE
Minimal example with button

### ISSUE THREAD

**Issue by ivanceras** [ryanmcgrath/cacao#1]
The library seems to have all the needed controls/widgets, but I'm struggling to add a button in a window.

**Comment by ryanmcgrath** [comment]
Is this for a sauron-native type deal, or for an app?

If the latter, unfortunately buttons work best inside toolbars right now - I have some updates pending but business has kept me busy the past month or two. Definitely welcome to outside contributions as well.

If the former, would be interested in what you need. :)

**Comment by ivanceras** [comment]
Yes, it would be for sauron-native. It would be great if there are more examples, showcasing the components. I would like to see how to embed each of these components. It would also be nice to see which child component is allowed in parent component.

**Comment by ryanmcgrath** [comment]
FYI, there's a `todos_list` and `calculator` example which showcase the framework better. It's still under heavy development so I'd caution against committing to it just yet, but wanted to follow up here for anyone interested.
