### ISSUE TITLE
MenuItem's objc pointer is private

### ISSUE THREAD

**Issue by 0123456789-jpg** [ryanmcgrath/cacao#118]
I recently found that the objc pointer held in cacao::appkit::menu::MenuItem is private when i want to do sth on the objc side.
Does anyone know why it's private?

**Comment by ryanmcgrath** [comment]
I'm confused - are you talking about this?

https://github.com/ryanmcgrath/cacao/blob/e3bbb9366c8cf5a5474c5b134ae60e9641da3b7b/src/appkit/menu/item.rs#L93

I feel like you should be able to just match on that enum and handle accordingly.

**Comment by 0123456789-jpg** [comment]
That's exactly what i want to say. My code works fine now. Thanks!
