### ISSUE TITLE
Why does only WebView implements 'fn did_load( &self,...)' with self as non-mut?

### ISSUE THREAD

**Issue by rrebelo62** [ryanmcgrath/cacao#14]
All controls implement `fn did_load( &mut self, ...` with self as mutable within did_load()

However WebView is the only exception, it implements self as non-mutable in `fn did_load( &self,...)`.

Is there a particular reason for this (e.g. fear of changes on non-UI threads)?

**Comment by ryanmcgrath** [comment]
Nope, 's probably just oversight on my part - `WebView` is actually the _oldest_ control here as it was the first ever created, and being behind the feature flag I've definitely missed a change there once or twice.

**Comment by rrebelo62** [comment]
Want me to fix it and PR it? :-)

**Comment by ryanmcgrath** [comment]
Def feel free!
