### ISSUE TITLE
webview compilation error

### ISSUE THREAD

**Issue by singhwong** [ryanmcgrath/cacao#16]
Hi,after I added cacao (v0.2.0) as a project dependency, when I introduced the webveiw scope, a compilation error occurred.
```
use cacao::webview::{WebView, WebViewConfig, WebViewDelegate};
```
error:
```
unresolved import `cacao::webview`

could not find `webview` in `cacao`rustc(E0432)
webview_custom_protocol.rs(5, 12): could not find `webview` in `cacao`
cacao-0.2.0/src/webview/mod.rs
```

**Comment by ryanmcgrath** [comment]
Hmmm, odd - someone else is using the webview pieces and compiling okay… can you share your Cargo.toml definition?

**Comment by singhwong** [comment]
Thank you for your reply, I found the problem! I did not add features in Cargo.toml.
