### ISSUE TITLE
`Info.plist` bundle

### ISSUE THREAD

**Issue by ghost** [ryanmcgrath/cacao#42]
I'm trying to integrate an `Info.plist` into a project using Cacao to set the `ATSApplicationFontsPath` key to load custom fonts. How is this possible?

**Comment by ghost** [comment]
I suppose this is part of bundles in general, which don't seem to be supported yet.

**Comment by ryanmcgrath** [comment]
You wouldn't use cacao for bundles, you'd use something like [cargo-bundle](https://crates.io/crates/cargo-bundle).

This project is very outdated but the scripts in the root should be more or less still the same approach you're looking for: https://github.com/secretkeysio/subatomic (look at the `release` and `debug` scripts)
