### ISSUE TITLE
Minimum system requirements

### ISSUE THREAD

**Issue by iMacker2020** [ryanmcgrath/cacao#78]
What are the official minimum system requirements for this project?
Rust version:
Mac OS version:
GNUStep version:

**Comment by ryanmcgrath** [comment]
Rust version, it probably works fairly far back... but the oldest I think I've recently tested against is ~`1.58`.

macOS, the code pays mind in places to more or less work as far back as Mojave (`10.14`), though it may also work for High Sierra (`10.13`). Keep in mind there are of course newer APIs/capabilities in modern macOS versions that the developer should be aware of.

GNUStep is a best-case-effort and it to my knowledge has not been hardcore tested, so if someone wants to tinker there and report back then they're more than welcome to.
