### ISSUE TITLE
Class with name RSTApplication could not be found

### ISSUE THREAD

**Issue by semtexzv** [ryanmcgrath/cacao#82]
I'm trying to build on top of trunk with some builder code for easier creation of simple UIs, but I keep hitting this error:

```
thread 'main' panicked at 'Class with name RSTApplication could not be found',
```

Occurs at https://github.com/ryanmcgrath/cacao/blob/a1f2711cebc1d429859e1fadf2f11ceed9e76987/src/appkit/app/mod.rs#L126

**Comment by ryanmcgrath** [comment]
Hmm, that's very odd - can you share a more full code sample that I could take a look at?

Chances are this just needs that `class!` call replaced with a `register...` call, but I'm curious if you have something else in the setup flow going on considering this isn't a widely reported bug.

(or if it's a regression here, somehow)

**Comment by semtexzv** [comment]
Occurs with running one of the examples for me.

**Comment by ryanmcgrath** [comment]
This should be fixed now - a recent PR somehow had tests pass automatically but introduced this bug, which I guess we need to look at... though the issue does come down to ObjC being possible to error at runtime, which this bug was. Compiler couldn't have caught it.
